# Generated by Django 4.0.5 on 2022-06-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'Estagiario'), ('As', 'Assistente'), ('JR', 'Junior'), ('PL', 'Pleno'), ('SR', 'Senior'), ('GR', 'Gerente')], max_length=2),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
